[tool.poetry]
name = "oarepo-model-builder"
version = "0.1.1"
description = "An utility library that generates OARepo required data model files from a JSON specification file"
authors = ["Miroslav Bauer <bauer@cesnet.cz>"]

packages = [
    { include = "oarepo_model_builder" }
]

[tool.poetry.dependencies]
python = ">=3.8,<4.0"
json5 = "^0.9.6"
deepmerge = "^0.3.0"
libcst = "^0.3.19"
munch = "^2.4.0"
click = ">=7.1"

[tool.poetry.dev-dependencies]
pytest = "^4.6"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.plugins."oarepo_model_builder.datamodel"]
datamodel = "oarepo_model_builder.handlers:DataModelBuilder"

[tool.poetry.plugins."oarepo_model_builder.elements"]
jsonschema = "oarepo_model_builder.builders.jsonschema_builder:JSONSchemaBuilder"
mapping = "oarepo_model_builder.builders.mapping:MappingBuilder"

[tool.poetry.scripts]
models = "oarepo_model_builder.cli:model"
