[tool.poetry]
name = "oarepo-model-builder"
version = "0.1.0"
description = "An utility library that generates OARepo required data model files from a JSON specification file"
authors = ["Miroslav Bauer <bauer@cesnet.cz>"]

packages = [
    { include = "oarepo_model_builder" }
]

[tool.poetry.dependencies]
python = "^3.9"
json5 = "^0.9.6"
deepmerge = "^0.3.0"

[tool.poetry.dev-dependencies]
oarepo = {extras = ["tests"], version = "^3.3.81"}

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.plugins."invenio_base.apps"]
oarepo_model_builder = "oarepo_model_builder.ext:OARepoModelBuilder"

[tool.poetry.plugins."invenio_base.api_apps"]
oarepo_model_builder = "oarepo_model_builder.ext:OARepoModelBuilder"

[tool.poetry.plugins."oarepo_model_builder.datamodel"]
datamodel = "oarepo_model_builder.handlers:DataModelBuilder"

[tool.poetry.plugins."oarepo_model_builder.elements"]
jsonschema = "oarepo_model_builder.builders.jsonschema_builder:JSONSchemaBuilder"
mapping = "oarepo_model_builder.builders.mapping:MappingBuilder"

[tool.poetry.plugins."flask.commands"]
model = "oarepo_model_builder.cli:model"
